name: ESLint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v7

    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint
